# Generated by Django 6.0.5 on 2026-05-07 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=9)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_path', models.CharField(max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('weeks_data', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='curriculum_analyzer.batch')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('report_status', models.CharField(default='pending', max_length=50)),
                ('detected_topic', models.CharField(blank=True, default='', max_length=500)),
                ('subtopics', models.JSONField(blank=True, default=list)),
                ('whats_good', models.JSONField(blank=True, default=list)),
                ('needs_improvement', models.JSONField(blank=True, default=list)),
                ('ai_suggestions', models.JSONField(blank=True, default=list)),
                ('quick_fixes', models.JSONField(blank=True, default=list)),
                ('category_scores', models.JSONField(blank=True, default=dict)),
                ('score_trend', models.JSONField(blank=True, default=list)),
                ('improvement_summary', models.JSONField(blank=True, default=dict)),
                ('previous_score', models.IntegerField(default=0)),
                ('performance_change', models.FloatField(default=0.0)),
                ('categories_improved', models.IntegerField(default=0)),
                ('categories_total', models.IntegerField(default=0)),
                ('full_report', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='curriculum_analyzer.curriculum')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
